from raise_error_add_assert import validate_user
validate_user([3], 1)
